[project]
name = "scope-backend"
version = "0.0.1"

[tool.black]
line-length = 79
exclude = '''
/(
    venv
  | \.venv
  | __pycache__
)/
'''

[tool.isort]
include_trailing_comma = true
line_length = 79
lines_after_imports = 2
known_first_party = ["users"]
skip = ["__init__.py", ".venv", "venv"]
